language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
  - pypy
  - coverage
install:
  - pip install tox-travis coveralls
script:
  - tox
notifications:
    email: false
after_success:
  - coveralls
